### ISSUE TITLE
About slice gaussian

### ISSUE THREAD

**Issue by lingxin12** [intel/ndg-fitting#9]
Nice work!
I cant understand the function because it is different from my deduction. Example for, the cov_3d should be cov_6d[:3,:3] = v_11, but the code is v_11 - v_12\*v_22_inv\*v_21. And the calculation of the 3d means and the pdf is confusing for me.
Could you offer the detailed deduction for the slice gaussian.
```python
def slice_gaussian(m, q, v, c_dim):
    v_11 = v[:, :c_dim, :c_dim]
    v_12 = v[:, :c_dim, c_dim:]
    v_21 = v[:, c_dim:, :c_dim]
    v_22 = v[:, c_dim:, c_dim:]

    v_22_inv = v_22.inverse()

    v_regr = torch.bmm(v_12, v_22_inv)

    m_1 = m[:, :c_dim]
    m_2 = m[:, c_dim:]
    x = q-m_2

    pdf_cond = torch.exp(-torch.abs(torch.bmm(torch.bmm(x.unsqueeze(-2), v_22_inv), x.unsqueeze(-1))))[:, :, 0]

    m_cond = m_1 + torch.bmm(v_regr, x.unsqueeze(-1))[:, :, 0]
    v_cond = v_11 - torch.bmm(v_regr, v_21)

    return m_cond, v_cond, pdf_cond

```

**Comment by diolatzis** [comment]
Hi! This function is taking into account the anisotropy of the 6D Gaussian to compute the 3D covariance and mean. If you just assume that the cov_6d[:3,:3] elements are the 3D covariance you would be ignoring that anisotropy.

In practice this means that the 3D Gaussian is changing shape and position as the viewing direction changes which is why it makes this a powerful representation for reflections. The pdf computation again adjusts the fact that the maximum pdf in the projected Gaussian is smaller than the pdf of the whole 6D Gaussian. 

This is somewhat explained here: https://en.wikipedia.org/wiki/Multivariate_normal_distribution#Conditional_distributions

Hope this helps!

**Comment by lingxin12** [comment]
Thanks very much for your reply!!!
